name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.0
          gemfile: Gemfile
          vault: true
        - ruby: 3.0
          gemfile: gemfiles/activesupport61.gemfile
        - ruby: 2.7
          gemfile: gemfiles/activesupport60.gemfile
        - ruby: 2.6
          gemfile: gemfiles/activesupport52.gemfile
        - ruby: 2.5
          gemfile: gemfiles/activesupport51.gemfile
        - ruby: 2.4
          gemfile: gemfiles/activesupport50.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test

    - if: ${{ matrix.vault }}
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install vault
        vault server -dev &
        sleep 1
        vault secrets enable transit
        vault write -f transit/keys/my-key derived=true
        vault audit enable file file_path=vault_audit.log
        bundle exec rake test
      env:
        KMS_KEY_ID: vault/my-key
        VAULT_ADDR: http://127.0.0.1:8200
