name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            gemfile: gemfiles/activesupport81.gemfile
          - ruby: 3.4
            gemfile: Gemfile
            vault: true
          - ruby: 3.3
            gemfile: gemfiles/activesupport72.gemfile
            openbao: true
          - ruby: 3.2
            gemfile: gemfiles/activesupport71.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test

      - if: ${{ matrix.vault }}
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install vault
          vault server -dev &
          sleep 1
          vault secrets enable transit
          vault write -f transit/keys/my-key derived=true
          vault audit enable file file_path=vault_audit.log
          bundle exec rake test
        env:
          KMS_KEY_ID: vault/my-key
          VAULT_ADDR: http://127.0.0.1:8200

      - if: ${{ matrix.openbao }}
        run: |
          wget -q -O bao.deb https://github.com/openbao/openbao/releases/download/v2.3.1/bao_2.3.1_linux_amd64.deb
          sudo dpkg -i bao.deb
          bao server -dev &
          sleep 1
          bao secrets enable transit
          bao write -f transit/keys/my-key derived=true
          bao audit enable file file_path=vault_audit.log
          bundle exec rake test
        env:
          KMS_KEY_ID: vault/my-key
          VAULT_ADDR: http://127.0.0.1:8200
